### ISSUE TITLE
US Ascii error and Syntax error

### ISSUE THREAD

**Issue by ColdBlooder** [mpapis/cinch-url-scraper#5]
I got the following error when i installed the plugin into my bot:

``` ruby
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require': /var/lib/gems/1.9.1/gems/cinch-url-scraper-1.2.0/lib/cinch/plugins/urlscraper.rb:156: invalid multibyte char (US-ASCII) (SyntaxError)
/var/lib/gems/1.9.1/gems/cinch-url-scraper-1.2.0/lib/cinch/plugins/urlscraper.rb:156: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/cinch-url-scraper-1.2.0/lib/cinch/plugins/urlscraper.rb:156: syntax error, unexpected $end, expecting ')'
...ot.debug("#{self.class.name} → #{config[:enabled_channels]...
...                               ^
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from Miyamoto.rb:13:in `<main>'
```

**Comment by Namasteh** [comment]
Was this error triggered on start-up?

**Comment by ColdBlooder** [comment]
Yes, right on startup

**Comment by Namasteh** [comment]
I just freshly installed the gem and ran a test instance of it within my testing bot, there were no issues present. 

Are you using the installed gem? Did you make any modifications?

**Comment by ColdBlooder** [comment]
I used the installed gem and made no modifications. I will reinstall it and try again

**Comment by Namasteh** [comment]
Please do, and report back :)

-Rick

**Comment by ColdBlooder** [comment]
I reinstalled it and it still happenes. But boots fine when i comment the plugin out. So it is the plugin causing the error.

**Comment by Namasteh** [comment]
Interesting, we'll take a look at it.

**Comment by ColdBlooder** [comment]
Ok, thanks!

**Comment by mpapis** [comment]
This problem usually happens when there is no LANG environment variable,
try:

echo ${LANG:-missing}

If it is missing or does not include utf8 them that is the problem

**Comment by ColdBlooder** [comment]
"de_DE.UTF-8"

Thats the whole output. Do i need the english (en_US.UTF-8) aswell?

**Comment by mpapis** [comment]
Is the LANG also set when you start the bot or it is all still in
development?

**Comment by ColdBlooder** [comment]
I don't have set any language options in the bot. So i presume the bot is using the same setting

**Comment by mpapis** [comment]
In some situations like init.d scripts or good or bluepill you need to set
LANG explicitly

**Comment by ColdBlooder** [comment]
locale for system wide use is set with "LANG=de_DE.UTF-8". Do i need to explcitly tell the bot to use the same setting? I also have en_US.UTF-8 installed.

**Comment by ColdBlooder** [comment]
Sry, i need to go to bed now. Its 2:15am over here. If you want me to try something else, just message me here :) And thanks for looking into the issue :)

**Comment by mpapis** [comment]
I guess we missed to ask most important question - how do you start it, do
you get more info if you prefix the command with: ruby -wdS

**Comment by ColdBlooder** [comment]
I just start it with ruby <filename>.rb

Starting the bot with the -wdS prefix reveals a ton of error messages. Looks like it can't load any files when im using that prefix:

http://pastebin.com/eC1G7buR

(Too big to post here, so i made a pastebin)

**Comment by mpapis** [comment]
can you [gist](https://gsit.github.com) `gem list -d`

**Comment by ColdBlooder** [comment]
https://gist.github.com/ColdBlooder/11214568

I only use  a few of them though. Not sure where half of them come from, lol.

**Comment by mpapis** [comment]
released `1.2.1` - it will fix this particular problem, but you still have `LANG` issue - you might hit it again

**Comment by ColdBlooder** [comment]
I just made the changed the arrow to => in the urlscraper.rb. It works now. Thanks! 

But what do you mean with lang issue?

**Comment by mpapis** [comment]
the char code in there was http://unicode-table.com/en/#2192 and it should be recognized by your charset, but it was not, my guess is your `LANG` was not read or interpreted properly by `ruby`

**Comment by ColdBlooder** [comment]
Well im using the UTF-8 charset. But i'll recheck my config. Thanks for your time!
