### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by mpapis** [mpapis/cinch-url-scraper#6]
```
Building gem ...
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
```

**Comment by Namasteh** [comment]
What license are we using?

**Comment by mpapis** [comment]
I have not decided yet, but I'm all for LGPL3 which means for me "use it how you like but share back your modifications to my code"

**Comment by Namasteh** [comment]
As am I. That's what really builds intelligent code.

**Comment by mpapis** [comment]
you can add it if you have some free time

**Comment by Namasteh** [comment]
Yeah, I can do that, does that change the version?

**Comment by mpapis** [comment]
no need I guess, we can release it with next fix / update

**Comment by Namasteh** [comment]
Sounds good to me

**Comment by Namasteh** [comment]
Updated License.

**Comment by mpapis** [comment]
awesome, thank you!
